In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import seaborn

In [2]:
teste = pd.read_csv('2019.csv', sep=';')

In [3]:
teste.columns = ['regiao', 'uf', 'cidade', 'sexo', 'faixaEtaria', 'dataFinalizacao', 'tempoResposta', 'nomeFantasia', 'segmentoMercado', 'area', 'assunto', 'grupoProblema', 'problema', 'formaContratacao', 'procurouEmpresa', 'respondida', 'situacao', 'avaliacaoReclamacao', 'notaConsumidor', 'total']

In [4]:
teste.head(1)

,regiao,uf,cidade,sexo,faixaEtaria,dataFinalizacao,tempoResposta,nomeFantasia,segmentoMercado,area,assunto,grupoProblema,problema,formaContratacao,procurouEmpresa,respondida,situacao,avaliacaoReclamacao,notaConsumidor,total
0,SE,RJ,Papucaia,F,entre 61 a 70 anos,30/01/2019,3.0,Banco Pan,"Bancos, Financeiras e Administradoras de Cartão",Serviços Financeiros,Crédito Consignado (Empréstimo descontado em f...,Cobrança / Contestação,Dificuldade para obter boleto de quitação ou i...,Telefone,S,S,Finalizada avaliada,Não Resolvida,1.0,1

In [5]:
teste.count()

regiao                 421336
uf                     421336
cidade                 421336
sexo                   421336
faixaEtaria            421336
dataFinalizacao        421336
tempoResposta          415376
nomeFantasia           421336
segmentoMercado        421336
area                   421336
assunto                421336
grupoProblema          421336
problema               421336
formaContratacao       421336
procurouEmpresa        421336
respondida             421336
situacao               421336
avaliacaoReclamacao    421336
notaConsumidor         242308
total                  421336
dtype: int64

In [6]:
teste['notaConsumidor'].mode()

0    5.0
dtype: float64

In [7]:
teste_original = teste.copy()

In [8]:
teste['notaConsumidor'].fillna(teste['notaConsumidor'].mode()[0], inplace=True)

In [9]:
teste.count()

regiao                 421336
uf                     421336
cidade                 421336
sexo                   421336
faixaEtaria            421336
dataFinalizacao        421336
tempoResposta          415376
nomeFantasia           421336
segmentoMercado        421336
area                   421336
assunto                421336
grupoProblema          421336
problema               421336
formaContratacao       421336
procurouEmpresa        421336
respondida             421336
situacao               421336
avaliacaoReclamacao    421336
notaConsumidor         421336
total                  421336
dtype: int64

In [10]:
teste['tempoResposta'].fillna(teste['tempoResposta'].mode()[0], inplace=True)

In [11]:
teste = teste.drop(['nomeFantasia', 'dataFinalizacao', 'cidade', 'problema', 'segmentoMercado','assunto','regiao'], axis = 1)

In [12]:
teste.head()

,uf,sexo,faixaEtaria,tempoResposta,area,grupoProblema,formaContratacao,procurouEmpresa,respondida,situacao,avaliacaoReclamacao,notaConsumidor,total
0,RJ,F,entre 61 a 70 anos,3.0,Serviços Financeiros,Cobrança / Contestação,Telefone,S,S,Finalizada avaliada,Não Resolvida,1.0,1
1,RJ,M,entre 31 a 40 anos,0.0,Serviços Financeiros,Informação,Telefone,S,S,Finalizada avaliada,Não Resolvida,1.0,1
2,SP,M,entre 31 a 40 anos,2.0,Produtos de Telefonia e Informática,Saúde e Segurança,Internet,N,S,Finalizada avaliada,Não Resolvida,1.0,1
3,SP,M,entre 51 a 60 anos,1.0,Telecomunicações,Cobrança / Contestação,Internet,S,S,Finalizada avaliada,Resolvida,5.0,1
4,SP,F,entre 21 a 30 anos,0.0,Serviços Financeiros,Informação,Internet,N,S,Finalizada avaliada,Não Resolvida,1.0,1

In [13]:
teste.dtypes

uf                      object
sexo                    object
faixaEtaria             object
tempoResposta          float64
area                    object
grupoProblema           object
formaContratacao        object
procurouEmpresa         object
respondida              object
situacao                object
avaliacaoReclamacao     object
notaConsumidor         float64
total                    int64
dtype: object

In [14]:
teste['sexo'] = teste['sexo'].apply(lambda x: 1 if x == 'male' else 0)

In [15]:
teste = pd.get_dummies(teste)

In [16]:
teste.head()

,sexo,tempoResposta,notaConsumidor,total,uf_AC,uf_AL,uf_AM,uf_AP,uf_BA,uf_CE,...,formaContratacao_Telefone,procurouEmpresa_N,procurouEmpresa_S,respondida_N,respondida_S,situacao_Finalizada avaliada,situacao_Finalizada não avaliada,avaliacaoReclamacao_Não Avaliada,avaliacaoReclamacao_Não Resolvida,avaliacaoReclamacao_Resolvida
0,0,3.0,1.0,1,0,0,0,0,0,0,...,1,0,1,0,1,1,0,0,1,0
1,0,0.0,1.0,1,0,0,0,0,0,0,...,1,0,1,0,1,1,0,0,1,0
2,0,2.0,1.0,1,0,0,0,0,0,0,...,0,1,0,0,1,1,0,0,1,0
3,0,1.0,5.0,1,0,0,0,0,0,0,...,0,0,1,0,1,1,0,0,0,1
4,0,0.0,1.0,1,0,0,0,0,0,0,...,0,1,0,0,1,1,0,0,1,0

In [17]:
alvo = teste["notaConsumidor"]

In [18]:
teste =  teste.drop('notaConsumidor', axis = 1)
teste.columns

Index(['sexo', 'tempoResposta', 'total', 'uf_AC', 'uf_AL', 'uf_AM', 'uf_AP',
       'uf_BA', 'uf_CE', 'uf_DF', 'uf_ES', 'uf_GO', 'uf_MA', 'uf_MG', 'uf_MS',
       'uf_MT', 'uf_PA', 'uf_PB', 'uf_PE', 'uf_PI', 'uf_PR', 'uf_RJ', 'uf_RN',
       'uf_RO', 'uf_RR', 'uf_RS', 'uf_SC', 'uf_SE', 'uf_SP', 'uf_TO',
       'faixaEtaria_até 20 anos', 'faixaEtaria_entre 21 a 30 anos',
       'faixaEtaria_entre 31 a 40 anos', 'faixaEtaria_entre 41 a 50 anos',
       'faixaEtaria_entre 51 a 60 anos', 'faixaEtaria_entre 61 a 70 anos',
       'faixaEtaria_mais de 70 anos', 'area_Alimentos', 'area_Demais Produtos',
       'area_Demais Serviços ', 'area_Educação', 'area_Habitação',
       'area_Produtos Eletrodomésticos e Eletrônicos',
       'area_Produtos de Telefonia e Informática', 'area_Saúde',
       'area_Serviços Financeiros', 'area_Telecomunicações',
       'area_Transportes', 'area_Turismo/Viagens', 'area_Água, Energia, Gás',
       'grupoProblema_Atendimento / SAC',
       'grupoProblema_Cobrança / Contestação',
       'grupoProblema_Contrato / Oferta', 'grupoProblema_Entrega do Produto',
       'grupoProblema_Informação', 'grupoProblema_Saúde e Segurança',
       'grupoProblema_Vício de Qualidade', 'formaContratacao_Catálogo',
       'formaContratacao_Domicílio', 'formaContratacao_Ganhei de presente',
       'formaContratacao_Internet', 'formaContratacao_Loja física',
       'formaContratacao_Não comprei / contratei',
       'formaContratacao_SMS / Mensagem de texto',
       'formaContratacao_Stand, feiras e eventos', 'formaContratacao_Telefone',
       'procurouEmpresa_N', 'procurouEmpresa_S', 'respondida_N',
       'respondida_S', 'situacao_Finalizada avaliada',
       'situacao_Finalizada não avaliada', 'avaliacaoReclamacao_Não Avaliada',
       'avaliacaoReclamacao_Não Resolvida', 'avaliacaoReclamacao_Resolvida'],
      dtype='object')

In [19]:
from sklearn.model_selection import train_test_split

X_treino, X_teste, Y_treino, Y_teste = train_test_split(teste, alvo, test_size = 0.22, random_state = 0)

In [20]:
X_treino.describe()

,sexo,tempoResposta,total,uf_AC,uf_AL,uf_AM,uf_AP,uf_BA,uf_CE,uf_DF,...,formaContratacao_Telefone,procurouEmpresa_N,procurouEmpresa_S,respondida_N,respondida_S,situacao_Finalizada avaliada,situacao_Finalizada não avaliada,avaliacaoReclamacao_Não Avaliada,avaliacaoReclamacao_Não Resolvida,avaliacaoReclamacao_Resolvida
count,328642.0,328642.000000,328642.0,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,...,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000,328642.000000
mean,0.0,6.677238,1.0,0.003393,0.006192,0.009396,0.001628,0.047441,0.027623,0.045530,...,0.220587,0.214464,0.785536,0.014265,0.985735,0.574662,0.425338,0.425293,0.192663,0.382045
std,0.0,3.281622,0.0,0.058149,0.078446,0.096478,0.040315,0.212580,0.163890,0.208463,...,0.414643,0.410451,0.410451,0.118580,0.118580,0.494395,0.494395,0.494388,0.394391,0.485888
min,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,4.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.0,8.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.0,9.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,0.0,15.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [21]:
Y_treino.describe()

count    328642.000000
mean          4.020999
std           1.554291
min           1.000000
25%           3.000000
50%           5.000000
75%           5.000000
max           5.000000
Name: notaConsumidor, dtype: float64

In [22]:
resultados ={}

In [23]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

gaussian = GaussianNB()
gaussian.fit(X_treino, Y_treino)
Y_pred = gaussian.predict(X_teste)
acc_gaussian = round(accuracy_score(Y_pred, Y_teste) * 100, 2)
resultados[acc_gaussian] = gaussian

In [24]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

logreg = LogisticRegression()
logreg.fit(X_treino, Y_treino)
Y_pred = logreg.predict(X_teste)
acc_logreg = round(accuracy_score(Y_pred, Y_teste) * 100, 2)
resultados[acc_logreg] = logreg

In [ ]:
# Support Vector Machines
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svc = SVC()
svc.fit(X_treino, Y_treino)
Y_pred = svc.predict(X_teste)
acc_svc = round(accuracy_score(Y_pred, Y_teste) * 100, 2)
resultados[acc_svc] = svc

In [ ]:
# Linear SVC
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

linear_svc = LinearSVC()
linear_svc.fit(X_treino, Y_treino)
Y_pred = linear_svc.predict(X_teste)
acc_linear_svc = round(accuracy_score(Y_pred, Y_teste) * 100, 2)
resultados[acc_linear_svc] = linear_svc

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

decisiontree = DecisionTreeClassifier()
decisiontree.fit(X_treino, Y_treino)
Y_pred = decisiontree.predict(X_teste)
acc_decisiontree = round(accuracy_score(Y_pred, Y_teste) * 100, 2)
resultados[acc_decisiontree] = decisiontree

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

randomforest = RandomForestClassifier()
randomforest.fit(X_treino, Y_treino)
Y_pred = randomforest.predict(X_teste)
acc_randomforest = round(accuracy_score(Y_pred, Y_teste) * 100, 2)
resultados[acc_randomforest] = randomforest

In [ ]:
resultados